// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxjwvcckvkaRXK_gOM0gUHS3gIZVhZCds',
    appId: '1:1034442476759:web:fdab1c88d553975ad77492',
    messagingSenderId: '1034442476759',
    projectId: 'food-nanda',
    authDomain: 'food-nanda.firebaseapp.com',
    storageBucket: 'food-nanda.firebasestorage.app',
    measurementId: 'G-M2RNRGJ7MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-wBilmfRZzy8aXd_8vG6CwVBqk0d8cVA',
    appId: '1:1034442476759:android:3713924acec19934d77492',
    messagingSenderId: '1034442476759',
    projectId: 'food-nanda',
    storageBucket: 'food-nanda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClP81IsXjN6NtFZVeYOPJVGXJlfeRtknk',
    appId: '1:1034442476759:ios:c20c4d8b0621edd6d77492',
    messagingSenderId: '1034442476759',
    projectId: 'food-nanda',
    storageBucket: 'food-nanda.firebasestorage.app',
    iosBundleId: 'com.example.utsnanda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClP81IsXjN6NtFZVeYOPJVGXJlfeRtknk',
    appId: '1:1034442476759:ios:c20c4d8b0621edd6d77492',
    messagingSenderId: '1034442476759',
    projectId: 'food-nanda',
    storageBucket: 'food-nanda.firebasestorage.app',
    iosBundleId: 'com.example.utsnanda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxjwvcckvkaRXK_gOM0gUHS3gIZVhZCds',
    appId: '1:1034442476759:web:6242d9bb257e26e1d77492',
    messagingSenderId: '1034442476759',
    projectId: 'food-nanda',
    authDomain: 'food-nanda.firebaseapp.com',
    storageBucket: 'food-nanda.firebasestorage.app',
    measurementId: 'G-FNN6WNJN3G',
  );
}
